name: AWSMockBuild
on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        run: |
          VERSION=$(cat version.txt)
          cd docker 
          docker build --no-cache --build-arg GH_TOKEN=${GH_TOKEN} -t awsmock-ui:$VERSION .

  push_to_registry:
    if: github.event.pull_request.merged == true
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag images
        run: |
          VERSION=$(cat version.txt)
          docker tag awsmock-ui:$VERSION ${{ secrets.DOCKER_USER }}/awsmock-ui:$VERSION
          docker push ${{ secrets.DOCKER_USER }}/awsmock-ui:$VERSION
          docker tag awsmock-ui:$VERSION ${{ secrets.DOCKER_USER }}/awsmock-ui:latest
          docker push ${{ secrets.DOCKER_USER }}/awsmock-ui:latest
