on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  release-please:
    runs-on: self-hosted
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GH_AUTH_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json